{% set version = "1.3.2" %}

package:
  name: pymt
  version: {{ version }}

source:
  url: https://github.com/csdms/pymt/archive/v{{ version }}.tar.gz
  sha256: 0137bccb5a6070dc99f3914bd85eea603cbe96ec9ba2cf32cfab99066f0f7ddb

build:
  number: 0
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - numpy
    - cython
    - gimli.units
  run:
    - python
    - numpy
    - scipy
    - matplotlib-base
    - xarray
    - shapely
    - netcdf4
    - pyyaml
    - jinja2
    - model_metadata
    - landlab
    - deprecated
    - gimli.units
    - esmpy
    - pymt_cem  # [not win]
    - pymt_child
    - pymt_hydrotrend
    - pymt_permamodel
    - pymt_sedflux  # [not win]

test:
  requires:
    - pytest
  imports:
    - pymt
  commands:
    # 1 test failing but it is a flaky repr comparison
    # - pytest --pyargs pymt --doctest-modules -o doctest_optionflags="NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL ALLOW_UNICODE"

about:
  home: https://github.com/csdms/pymt
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: Python package that provides services for coupling BMI components
  description: |
    PyMT is an Open Source Python package, developed by the Community
    Surface Dynamics Modeling System, that provides the necessary
    tools used for the coupling of models that expose the Basic
    Modeling Interface (BMI). It contains,
    *  Tools necessary for coupling models of disparate time and space
       scales (including grid mappers)
    *  Time-steppers that coordinate the sequencing of coupled models
    *  Exchange of data between BMI-enabled models
    *  Wrappers that automatically load BMI-enabled models into the
       PyMT framework
    *  Utilities that support open-source interfaces (UGRID, SGRID,
       CSDMS Standard Names, etc.)
    *  A collection of community-submitted models, written in a variety
       of programming languages, from a variety of process domains - but
       all usable from within the Python programming language
    *  A plug-in framework for adding additional BMI-enabled models to
       the framework
  doc_url: https://pymt.readthedocs.io
  dev_url: https://github.com/csdms/pymt

extra:
  recipe-maintainers:
    - mcflugen
