travis:
  secure:
    BINSTAR_TOKEN: kgUzRgfF2SpNrPFpawV4+RdduCI4A2PniHiRc3HJVDgM/+fMBerZgXQCnKx4UTxFbxguGCWHmJhQlvg1+onuofipmU17iUksJXDb9LnPrrmojSMKrovMWGOtqFH4UTx+6Vv0NzR3BQuU8oswTzFUtig5JSsLtidqSV2tKuXkT0v30sDr/FrkKhRDMLF3oQbAdXyAMQHzldoUgnjo2ZiNd1Fi/M7H4czbMNDhGHgtnXz+NGhiD9BW7BagxB0GffABFgI0PvRVRWkteBW8skiUg3CtAA8v2UQsNYFpgp+jciiKK4YCRDb4gLCaq7GAj/Yc/XTpkVrQgCl8M8lgJsQk92hXZ6VbGWtiE6MJmLPPpaOGMbJAnfla/8RYXQOJwzmCoB14KazJQQcAjFwhGHx2pjlmORa9QsxuFwt4CYF9tZVB/dCEjXYheQy+/bMcJ+sfmtrF36m25kFe1662jj4z5PMaxoCuMuRZcY7SDJFgbmIrf6piwcVk3hbF1ftFG+ImJKC5l2NpW9djU6K9mxS2MK2fcJ8k34qiyTSSSC5JVjVTryNryW/r58MMkCkMNywzdpg4SshVFARNJ+txSnyFzPb4lNIBA8oMsXEUiF7sU1UeTUaLrR6BaaGcxCoyYHk0wmjg9v2c7GaeZk0WnA3J9oZm4ZO8uZLpHuUIvSedEnA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
