travis:
  secure:
    BINSTAR_TOKEN: ja3Ap/XeEdTVXdT1smqy4utBdVbtrB9ZM03ABA24EZZjZnfBF2Lvz7dGKq4GCfenPkTS6l3+a9Q866bLfp/mI+glYRdfxXJMHbEvF9QQMOtOErBH0nNlFoW04JpBqmJYU0/5pJ970jByfwmWfjBwUvEV7uLsdcbOSHa+uDhQRBbAjJQWFsj/jEfdzgClJKq891y/PJUwxO7FP1gFa0eXhsudT6HUoLIuBClJ/hxRUxtMgycI3UlL7Py4miOrYiuFZBj67MKxLxQQtaY9//SR1nyU96e4udHV4gp82QouQniv/Rf/Pr/GKJqX2shJud1lD0akjUvgJ6Olacw6Wy9RUOVW+N/c5tJntiV27j/0eAaKwDRJOFAauQCSo4Myy4/Vh/oQHEufB62mouglO5M1pWe0948qZqt8cttJ0mJ1mmM9pWQ89/Vx+N63hvRrTZ8U7HnDdwdyF7L/wVrxK15fk6opWeDrcGrlrDOTf0Uxo2oRcgyCSvSRogeXBGjgh/vpSsgn546DXqx3PKPFA6xbzziLkYk3avqkae4lYfZd4uDsXs5qK/RfqoOlRy7bLqaBV36eeEp0PZoXFzaMueiq9ddwMiJ78huQRNSFrpLwWlOL2LySyhyrAijVXeETpPvSlXhFlqBpuFQvQSGyDLYCMWwrun4f0b1l74Vfsr2uT2E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
